config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  get '/auth/github/callback', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  
  namespace :user, path: ':user' do
    get '/dashboard', to: 'dashboard#index'
    get '/stars', to: 'stars#index'
    get '/followers', to: 'followers#index'
    get '/following', to: 'following#index'
    get '/repos', to: 'repos#index'
    get '/organizations', to: 'organizations#index'
    get '/events', to: 'events#index'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/commit.rb
class Commit
  attr_reader :author_name, :commit_message, :commit_date, :sha
  def initialize(attrs = {})
    @sha = attrs[:sha]
    @author_name = attrs[:commit][:author][:name]
    @commit_message = attrs[:commit][:message]
    @commit_date = attrs[:commit][:author][:date]
  end

  def self.recent_commits(current_user)
    names = Repo.repo_names(current_user)
    repo_commits = Array.new
    names.each do |repo_name|
      hash = GithubService.new(current_user).get_recent_commits(repo_name)
      commits_for_repo = hash.map do |commit|
        Commit.new(commit)
      end
    repo_commits << {repo_name => commits_for_repo}
    end
  repo_commits
  end

end

app/models/event.rb
class Event
  include ActionView::Helpers::DateHelper
  attr_reader :event_type, :username, :repo, :created_at, :action
  def initialize(attrs = {})
    @event_type = attrs[:type]
    @username = attrs[:actor][:login]
    @repo = attrs[:repo][:name]
    @created_at = attrs[:created_at]
    @action = attrs[:payload][:action]
  end

  def self.activities(current_user)
    GithubService.new(current_user).get_recent_activity.map do |activity|
      Event.new(activity)
    end.take(30)
  end
end

app/models/follower.rb
class Follower
  attr_reader :avatar_url, :login, :html_url
  def initialize(attrs = {})
    @avatar_url = attrs[:avatar_url]
    @login = attrs[:login]
    @html_url = attrs[:html_url]
  end

  def self.followers(current_user)
    GithubService.new(current_user).get_followers.map do |repo|
      Follower.new(repo)
    end
  end
end

app/models/following.rb
class Following
  attr_reader :html_url, :login, :avatar_url
  def initialize(attrs = {})
    @html_url = attrs[:html_url]
    @login = attrs[:login]
    @avatar_url = attrs[:avatar_url]
  end

  def self.following(current_user)
    GithubService.new(current_user).get_following.map do |repo|
      Following.new(repo)
    end
  end
end

app/models/github_user.rb
class GithubUser
  attr_reader :service, :current_user
  def initialize(current_user)
    @service ||= GithubService.new(current_user)
    @current_user = current_user
  end

  def profile
    service.get_profile
  end

  def starred
    Star.stars(current_user)
  end

  def followers
    Follower.followers(current_user)
  end

  def following
    Following.following(current_user)
  end

  def repos
    Repo.repos(current_user)
  end

  def organizations
    Organization.organizations(current_user)
  end

  def recent_events
    Event.activities(current_user)
  end

  def activity_from_others
    OthersEvent.activities(current_user)
  end

  def recent_commits
    Commit.recent_commits(current_user)
  end

end

app/models/organization.rb
class Organization
  attr_reader :url, :avatar_url
  def initialize(attrs = {})
    @url = attrs[:url]
    @avatar_url = attrs[:avatar_url]
  end

  def self.organizations(current_user)
    GithubService.new(current_user).get_organizations.map do |repo|
      Organization.new(repo)
    end
  end
end

app/models/others_event.rb
class OthersEvent
  attr_reader :type, :login, :repo_name, :repo_url, :created_at
  def initialize(attrs = {})
    @type = attrs[:type]
    @login = attrs[:actor][:login]
    @repo_name = attrs[:repo][:name]
    @repo_url = attrs[:repo][:url]
    @created_at = attrs[:created_at]
  end

  def self.activities(current_user)
    GithubService.new(current_user).get_activity_from_others.map do |activity|
      OthersEvent.new(activity)
    end
  end
end

app/models/repo.rb
class Repo
  attr_reader :html_url, :name, :language, :updated_at
  def initialize(attrs = {})
    @html_url   = attrs[:html_url]
    @name       = attrs[:name]
    @language   = attrs[:language]
    @updated_at = attrs[:updated_at]
  end

  def self.repos(current_user)
    GithubService.new(current_user).get_repos.map do |raw_repo|
      Repo.new(raw_repo)
    end
  end

  def self.repo_names(current_user)
    GithubService.new(current_user).get_repos.map do |repo|
      repo[:name]
    end
  end
end

app/models/star.rb
class Star
  attr_reader :full_name, :description, :url, :forks_count, :updated_at
  def initialize(attrs = {})
    @full_name = attrs[:full_name]
    @description = attrs[:description]
    @url = attrs[:url]
    @forks_count = attrs[:forks_count]
    @updated_at = attrs[:updated_at]
  end

  def self.stars(current_user)
    GithubService.new(current_user).get_starred.map do |repo|
      Star.new(repo)
    end
  end
end

app/models/user.rb
class User < ApplicationRecord

  def self.from_github(data, access_token)
    user = User.find_or_create_by(uid: data["id"])
    user.username = data["login"]
    user.avatar = data["avatar_url"]
    user.token = access_token
    user.save

    return user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :authorize!

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authorize!
    unless current_user
      redirect_to root_path
    end
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authorize!

  def index
    @github_user = GithubUser.new(current_user)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authorize!
  @events = GithubUser.new(current_user).recent_events
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/repos_controller.rb
class ReposController < ApplicationController
  before_action :authorize!
  def index
    @repos = GithubUser.new(current_user).repos
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  attr_reader :access_token
  def create
    github_oauth = GithubOauth.new(params['code'])
    access_token = github_oauth.access_token
    data = github_oauth.data

    user = User.from_github(data, access_token)
    session[:user_id] = user.id
    redirect_to "/#{current_user.username}/dashboard"
  end

  def destroy
    session.clear

    redirect_to root_path
  end
end

app/controllers/user/dashboard_controller.rb
class User::DashboardController < ApplicationController
  before_action :authorize!

  def index
    @github_user = GithubUser.new(current_user)
  end
end

app/controllers/user/events_controller.rb
class User::EventsController < ApplicationController
  before_action :authorize!
  @events = GithubUser.new(current_user).recent_events
end

app/controllers/user/repos_controller.rb
class User::ReposController < ApplicationController
  before_action :authorize!
  def index
    @repos = GithubUser.new(current_user).repos
  end
end

app/controllers/user/stars_controller.rb
class User::StarsController < ApplicationController
  before_action :authorize!
  def index
    @stars = GithubUser.new(current_user).starred
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboard/index.html.erb
<div class="dashboard" style="width:800px; margin: 0 auto;">
  <div class="profile">
  <%= image_tag current_user.avatar, class: "avatar" %><br>
  <strong><%= @github_user.profile[:name] %></strong><br>
  <%= @github_user.profile[:login] %><br>
  <%= @github_user.profile[:email] %><br>
  <br>
  <%= link_to "Logout", logout_path, class: "button" %>
  <br><br>
  </div>
  <div class="links">
    <%= link_to "Stars", stars_path %> - <%= link_to "Followers", followers_path %>
    <%= @github_user.profile[:followers] %> - <%= link_to "Following", following_index_path %>
    <%= @github_user.profile[:following] %> - <%= link_to "Repositories", repos_path %>
    <hr>
</div>
<h3>Organizations</h3>
<center><%= @github_user.organizations.map do |organization| %>
  <%= image_tag organization.avatar_url, class: "img-rounded" %>
<% end %>
</center>
<hr>
<h3>My recent activity</h3>
  <%= @github_user.recent_events.map do |activity| %>
    <p><a href="https://www.github.com/<%= activity.repo %>"><%= activity.repo %></a>  <%= activity.event_type %>  <%= time_ago_in_words(activity.created_at) %> ago
  <% end %>
<hr>
<h3>Recent Activity from users I follow</h3>
<%= @github_user.activity_from_others.map do |activity| %>
  <p><a href="https://www.github.com/<%= activity.login %>" ><%= activity.login %></a>  <%= activity.type %>  <a href="https://github.com/<%= activity.repo_name %>" ><%= activity.repo_name %>  </a>  <%= time_ago_in_words(activity.created_at) %> ago </p>
<% end %>
</div>

app/views/stars/index.html.erb
<div class="dashboard" style="width:800px; margin: 0 auto;">
  <h1>Starred Repos</h1>
  <br>
    <% @stars.map do |repo| %>
      <p><a href="https://www.github.com/<%= repo.full_name %>"><%= repo.full_name %></a></p>
      <p><%= repo.description %></p>
      <p>Forks <%= repo.forks_count %> -  Updated at <%= time_ago_in_words(repo.updated_at) %></p>
      <hr>
    <% end %>
    <center><%= link_to "Return to Dashboard", dashboard_index_path, class: "button" %></center>
</div>